### ISSUE TITLE
[Neko] Primitive not found: lua@lua_create<0>

### ISSUE THREAD

**Issue by kevinresol** [MattTuttle/hx-lua#1]
I installed the lib with:
`haxelib git lua https://github.com/MattTuttle/hx-lua.git`

and then simply compiled the build.hxml then got the error.

**Comment by MattTuttle** [comment]
I may not have all of the ndlls up to date yet. Try `lime rebuild .` in the hx-lua directory and it should recompile the ndll for your platform.

**Comment by kevinresol** [comment]
Did I miss anything? `lime rebuild .` does not update the ndll files

**Comment by kevinresol** [comment]
Figured it out: it should be `lime rebuild lua windows`
